### ISSUE TITLE
Connection to camera not taking into account port and path

### ISSUE THREAD

**Issue by nelsondelmonte** [calebolson123/BabySleepCoach#1]
I could be mistaken but shouldn't line 552 in main.py be:

`c = cv2.VideoCapture(connect_str2)`

(changed from: `c = cv2.VideoCapture(connect_str)`)

I'm not much of a coder but I can fumble my way through and making that change allowed the code to run for me, it would error out prior to the change.

**Comment by calebolson123** [comment]
Hm, yeah try both out & see how it behaves. The `connection_str` likely will be dependent on your camera. I just went with what worked on my reolink cam. What kind of camera are you using (exact brand & model ideally)?

**Comment by nelsondelmonte** [comment]
I'm using a WyzeCam3 with a custom firmware to enable RTSP (wz_mini_hacks).

The RTSP URL is formed as follows:

`rtsp://user:pass@192.168.x.x:8554/unicast`

**Comment by calebolson123** [comment]
@nelsondelmonte I think you got this working? Will close this if so

**Comment by nelsondelmonte** [comment]
Yep, all good
