### ISSUE TITLE
qt.qpa.xcb: could not connect to display

### ISSUE THREAD

**Issue by TaintedIron** [calebolson123/BabySleepCoach#10]
I don't believe this issue has to do with the code, but I'm opening this just in case if anyone has faced this problem.

If I run `main.py` or debug it in VS Code I receive the below,

`qt.qpa.xcb: could not connect to display`

Need some help with this error when testing out this project with `recorded` video.  I'm pretty certain I have all the correct dependencies in place. I believe this part of the reason why I been having problems viewing the stream?

**Comment by calebolson123** [comment]
I ran into this error at one point trying to debug remotely from my desktop on raspberry pi... I believe I got it working by using some pretty google-able suggestions. Try `export DISPLAY=:0.0` in your command line

**Comment by TaintedIron** [comment]
@calebolson123 Thank you for the reply. I'm closing this issue since I haven't had time to work on this.
