### ISSUE TITLE
How to reposition the cropped image?

### ISSUE THREAD

**Issue by TaintedIron** [calebolson123/BabySleepCoach#17]
I probably could figure this out, but it has taken me a while to make it this far. In the screenshot below, I'm simply trying to reposition the cropped frame to be in the center. 

![image](https://github.com/calebolson123/BabySleepCoach/assets/59463977/f4207340-7574-4ff6-8e89-4cff8a46af28)

**Comment by calebolson123** [comment]
This will be made more obvious in some upcoming PRs, but with the version you have, you can update the position & size of the box here: https://github.com/calebolson123/BabySleepCoach/blob/master/main.py#L468

**Comment by TaintedIron** [comment]
@calebolson123 First, thank you for your swift response! I was able to reposition how I wanted.
