### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by DerArtz** [calebolson123/BabySleepCoach#19]
Might have missed something, but seems to be missing the `docker-compose.yml` file?

**Comment by calebolson123** [comment]
Ah my bad, I'll get it added. Thanks for pointing that out

**Comment by calebolson123** [comment]
Alright, just merged this: https://github.com/calebolson123/BabySleepCoach/pull/20

Give it another shot. Thanks for pointing this out @DerArtz
