### ISSUE TITLE
Idea for new feature

### ISSUE THREAD

**Issue by Kampi** [calebolson123/BabySleepCoach#27]
The idea was to expand the baby sleep monitor with some sort of automatism to activate a heating device for the feeding bottles during the night when the baby wakes up (maybe with some sort of WiFi plug). So you can stand up, grab the bottle, feed the baby, put a new bottle into the heating device, and go back to sleep 😄

**Comment by calebolson123** [comment]
Hah, had this idea back when I built [the hungry baby alarm](https://www.youtube.com/watch?v=Lda1Sq8HRY4). Was thinking if it detected the baby as hungry, it could just start preparing a bottle. Although this ventures into hardware where im a bit less comfortable
