### ISSUE TITLE
Seeking hardware recommendations

### ISSUE THREAD

**Issue by drewklein20** [calebolson123/BabySleepCoach#30]
This is not a burning issue, so feel free to deprioritize! Expecting father and tech enthusiast myself so I'm definitely going to give this project a try! Do you have any camera recommendations? Preferably WiFi but I could also run a POE camera pretty easily if it makes sense.

**Comment by drewklein20** [comment]
Also, do you have any suggestions for camera placement?

**Comment by albvar** [comment]
I have spent quite a bit of money on testing out cameras from wyze with custom firmware to support RTSP to my most recent
TAPO cameras. 

# Wyze Cameras v2 (not very good / wouldn't recommend / non-native RTSP support)

- I have constant issues with these, cheap wireless radio
- The USB power dongle on these goes bad after a while
- No native RTSP support, deep down I know they know their product hardware doesn't have a very good wireless antenna for continuous monitoring so they only made custom firmware just to appease a small portion of their user base. They seem to have abandoned RTSP support in their newer models. 

![image](https://github.com/calebolson123/BabySleepCoach/assets/10334630/8d34d1fb-80a5-4833-bcc4-1360fb37fd40)

# Tapo Wireless Cameras (great / would recommend / what I plan on using for this project / native RTSP support)

- Native support for RTSP tells me they have a nice wireless radio and they aren't trying to hide it like Wyze does. It's rare to find RTSP support on wireless products, so this says a lot to those that are informed about this topic.
- Maybe get one of their fixed cameras so this doesn't track other movement.
- Shouldn't require a raspberri pi as it has a built-in RTSP stream.

![image](https://github.com/calebolson123/BabySleepCoach/assets/10334630/037899f6-3a62-4a27-b408-8a78d5748434)

**Comment by calebolson123** [comment]
I don't have much experience/knowledge around other cameras, i picked up a pair of cheap outdoor reolink (RLC-410) security cameras and they were fine & worked well for my dog poop detector. I picked up the E1 Pro for baby's crib. That's the camera I used throughout development, and is in the video

**Comment by drewklein20** [comment]
Thank you for the suggestions!
