### ISSUE TITLE
Problems with webapp connection

### ISSUE THREAD

**Issue by rtxco** [calebolson123/BabySleepCoach#34]
For some reason I can't connect to <ip address>:<port of UI>
example: 192.xx.xxx.x:80  shows this below
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/af874640-4dc2-46af-8870-9fe7b555696f)

whereas 192.xx.xxx.x:8000 shows this  
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/6b4f8c99-fb6e-4a75-a610-5f980ddf0560)

These pictures are from my desktop browser. When I try connecting to these addresses on mobile, none of them work. Just "site can't be reached" 
I'm totally lost here. Any help is appreciated.

Running this on my desktop, firewalls are deactivated, Docker has been put on the Allow list for windows security. Getting the same issue

**Comment by rtxco** [comment]
I ran docker logs command and came up with this 
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/b0ea78a6-9180-4dfb-b44e-1e678d70ed03)
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/265e33ad-72a8-41da-966f-06fac4259af6)

**Comment by rtxco** [comment]
fixed by installing yarn in the webapp folder

**Comment by wouterverduin** [comment]
@rtxco How did you install yarn from the webapp folder? Thanks in advance!
