### ISSUE TITLE
Can't see video feed on webapp. 

### ISSUE THREAD

**Issue by rtxco** [calebolson123/BabySleepCoach#35]
I know the rtsp link is working because I can see it via VLC media player. I ran docker logs and came up with a bunch of errors I don't really understand. The webapp UI is visible, just no video feed. 
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/1557ef7d-c8e0-42a6-a78c-7597548f4cb1)

![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/c0abcee4-82b6-4363-8dd9-290699030afb)
 
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/3964ee95-4092-41ae-ac03-76ca00c86916)

![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/0d268cc7-5fa0-413c-a657-a6579a2f33a0)

**Comment by albvar** [comment]
Install net tools on the docker container and show us what ports are running. Then show us your F12 developer network tab show us errors reaching the stream.

**Comment by rtxco** [comment]
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/8a35b1ec-3f76-445d-997a-abceb53dcece)

![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/239b7365-51ca-4bac-9f94-80e76685d761)

@albvar hope this helps 

> Install net tools on the docker container and show us what ports are running. Then show us your F12 developer network tab show us errors reaching the stream.

**Comment by rtxco** [comment]
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/770878d0-6838-4668-8e03-937a1d384455)

**Comment by rtxco** [comment]
This might be a ridiculous question but am I entering the incorrect IP address? my public IP is different than the ip address i get from ipconfig. I have zero background in networking.  Which is the correct IP to use?

**Comment by rtxco** [comment]
@calebolson123 any help here? thanks in advance

**Comment by calebolson123** [comment]
Hey man, apologies for the difficulty in getting it all configured. As you can tell I don't work these projects full time, just as free time and willingness allows :). Hopefully I can help you get it up and running.

The environment variable most likely causing your issues is gonna be `CAM_URL`.  You should be able to use the same url you're using for VLC player, as part of that environment variable in the app. If you're running w/ docker-compose, it should load up your .env file. For sanity, I would suggest jumping into the container(`docker exec -it <container_id> bash`) and checking out your environment variables w/ `env | sort`. My full CAM_URL is: `CAM_URL=rtsp://username:pw@192.168.50.130:554/h264Preview_01_sub`. I just ran a fresh install on a mac and it all worked except for some startup issues highlighted in other gh issues.. i'll be addressing those in a PR soon here. It looks like you're beyond those issues, however.

Can you find the request matching this screenshot in your network console? This is the request which gets video frames from the server, and is subsequently rendered in browser

<img width="894" alt="image" src="https://github.com/calebolson123/BabySleepCoach/assets/21248639/0afe72ec-11f0-4ac0-beb3-dd25b2e256c4">

**Comment by calebolson123** [comment]
https://github.com/calebolson123/BabySleepCoach/pull/36

**Comment by rtxco** [comment]
@calebolson123 hey caleb thanks for the assistance. I ran the env | sort for peace of mind and returned this 

APP_DIR=/usr/app/babysleepcoach
CAM_URL=rtsp://user:pw@192.168.1.95:554/stream1
DEBUG=False
HATCH_IP=192.168.HATCH.IP
HOME=/root
HOSTNAME=7ec86f69a02c
NODE_VERSION=21.6.2
OWL=False
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PIP_BREAK_SYSTEM_PACKAGES=1
PORT=80
PWD=/usr/app/babysleepcoach
REACT_APP_BACKEND_IP=192.168.1.79:8001
REACT_APP_RESOURCE_SERVER_IP=192.168.1.79:8000
SHLVL=1
TERM=xterm
VIDEO_PATH=/usr/app/babysleepcoach/video
YARN_VERSION=1.22.19
_=/usr/bin/env
root@7ec86f69a02c:/usr/app/babysleepcoach#


So I think that checks out regarding the env file.

**Comment by rtxco** [comment]
@calebolson123 I changed the IP in the env file to just localhost as per your recent suggestion, and now i see this 
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/3dbe499a-ee17-4061-9801-b691b5c29d68)
So I guess there's something wrong with the request to get video frames which makes sense why I don't have a video feed. How do I fix this lol. My camera is working, I can see it on VLC with the exact same URL that's in my ENV. Ports are open. 

![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/2ec56f40-7328-49dd-935d-97f850eecd56)




![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/706d767f-e0c9-447f-8a9e-29ad2b4838e2)

**Comment by rtxco** [comment]
Not sure if this helps but when I go to the Request URL that is in that Raw header, it shows me this 
![image](https://github.com/calebolson123/BabySleepCoach/assets/159763018/8dbdc179-d1e9-4cf6-afd1-041a31fd6380)

**Comment by calebolson123** [comment]
Do you mind telling me what kind of camera you have?

Also, are you sure the trailing `/stream1` on your CAM_URL is correct? You have `/stream1` in the url used in vlc player? for my reolink camera, i use `/h264Preview_01_sub`.

**Comment by rtxco** [comment]
> Do you mind telling me what kind of camera you have?
> 
> Also, are you sure the trailing `/stream1` on your CAM_URL is correct? You have `/stream1` in the url used in vlc player? for my reolink camera, i use `/h264Preview_01_sub`.

Well I have no idea why or how, but I did a fresh install just like you mentioned, and it works. Using the exact same Cam url and other variables. I don't get it.  Haha. 

I do have a random question still, if I train this AI with say for example my wife, and then want to use it for the baby who isn't here yet, is there a way I can delete it's knowledge up till that point? Or does it require a fresh install.

**Comment by calebolson123** [comment]
Good deal, glad it's up. There are a lot of things I would do to improve this thing, but it limps along okay.. and I'm currently deep into another project. By open sourcing I was hoping others would be able to improve it further.

On the swapping of subjects: There's no built-in way of swapping subjects currently. But you can swap training data around if you move some files around. I don't have a clean set of steps right now, but if you trace the code around training, you can piece what it does together. If I recall correctly, I'm saving images to filesystem (`BabySleepCoach/blanket_model/input`) every time you click awake/asleep button. Then that file is read along w/ all prior samples collected, and used to create a new version of the model which reloaded in in real time.

So you could keep your labeled samples of your wife by just copying and pasting elsewhere, and clearing out the images in `blanket_model/input/*` & resetting `image_data.json` to look like: `{ "baby": [], "no_baby": [] }`. If i recall correctly, the JSON bit was just a speedup trick i came up w/ to get around reading and parsing all the sample images every time the user retrains the model.

If you 1) "reset" image_data.json & 2) remove the images under the input dir, and maybe a reboot, you should be able to wipe the system clean. `user_defined_crop_area.txt` is the other file that persists to fs.. this is where the bounding box of pixels the system actually processes on, is stored. This is for performance improvements. But if you're trying to wipe clean for your baby, I would just empty that file. The app should force you to reset the bounds

**Comment by calebolson123** [comment]
I'm going to close this, feel free to create new issues!
