### ISSUE TITLE
Refactor of code

### ISSUE THREAD

**Issue by nos86** [calebolson123/BabySleepCoach#5]
Hello @calebolson123 ,
I spent some time to refactor the code (my branch dev) in order to split code in different files for a better integration for other users. [https://github.com/nos86/BabySleepCoach/tree/dev](url)

Not all functions are currently re-implemented, but I need some support for debug.
Do you have some time to test my code and provide me some feedbacks on it?

currently env variable has not been reimplemented, so please change manually the VideoCapture string (main.py:105).

As soon as the debug is completed, I'll complete the implementation of missing functions and comment the code.
Feel free to reply to this topic listing all bugs / missing functions

Thanks in advance for your support,
Salvo

**Comment by calebolson123** [comment]
Hey man, awesome, thanks for your help cleaning this up. I can test it out once I get some time here. If you create a branch & PR on this repo it will be easier to iterate on changes and offer feedback. Just a suggestion

**Comment by nos86** [comment]
I'm do it..
