### ISSUE TITLE
noobie here - Resizing image missing argument

### ISSUE THREAD

**Issue by TaintedIron** [calebolson123/BabySleepCoach#7]
First time submitting an issue here on github. I'm getting the below issue when debugging in vscode on line 474 in main.py.
I'm not sure if this is caused by me or what. 

TypeError: maintain_aspect_ratio_resize() missing 1 required positional argument: 'image'

[https://github.com/calebolson123/BabySleepCoach/blob/bd9daff1e851b2f85fc1b46d687a497bc6da29e7/main.py#L474](url)

**Comment by calebolson123** [comment]
Hey @TaintedIron, curious, do you see the same error when you run the app, or is vscode just complaining about it?

Another thing to try: remove `self` from args in `maintain_aspect_ratio_resize()` (helpers.py)... there's a PR open here: https://github.com/calebolson123/BabySleepCoach/pull/6/files#diff-f7c0aa3074afdefcafb9cea771d056731f45608330aac2f47ce6788aff20baccR111 which drops the self arg

**Comment by TaintedIron** [comment]
Hi @calebolson123, error occurred when running the app. Your suggestion to remove `self` from args in `maintain_aspect_ratio_resize()` worked. I also had to do the same in `gamma_correction()`.

**Comment by calebolson123** [comment]
Good stuff, best of luck
